version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"

    volumes:
      - "./bridge:/usr/src/app/bridge"
    restart: 'no'
    command: gunicorn bridge.asgi:app -w 1 -k uvicorn.workers.UvicornWorker
    networks:
      - bridge-net


  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: "no"
    networks:
      - bridge-net


volumes:
  db-data:


networks:
  bridge-net: